import {
  SearchResultsData,
  SearchResultsTab,
} from "./searchResultsTypes";

export const searchResultsTabs: SearchResultsTab[] = [
  { label: "All", value: "all" },
  { label: "Courses", value: "courses" },
  { label: "Instructors", value: "instructors" },
  { label: "Live Classes", value: "live-classes" },
];

export const mockSearchResults: SearchResultsData = {
  courses: {
    relevant: [
      {
        id: "course-react-foundations",
        title: "React Foundations for Production Apps",
        instructor: "Maya Chen",
        level: "Beginner",
        duration: "9h 20m",
        lessons: 46,
        rating: 4.9,
        students: "18.4k",
        price: "$49",
        badge: "Best match",
        accent: "from-sky-500 to-cyan-400",
      },
      {
        id: "course-next-app-router",
        title: "Next.js App Router Masterclass",
        instructor: "Omar Hassan",
        level: "Intermediate",
        duration: "12h 10m",
        lessons: 58,
        rating: 4.8,
        students: "12.7k",
        price: "$69",
        badge: "Popular",
        accent: "from-indigo-500 to-sky-400",
      },
      {
        id: "course-typescript-react",
        title: "TypeScript Patterns for React Teams",
        instructor: "Nora Ellis",
        level: "Advanced",
        duration: "7h 45m",
        lessons: 34,
        rating: 4.9,
        students: "9.1k",
        price: "$59",
        badge: "Team pick",
        accent: "from-emerald-500 to-teal-400",
      },
      {
        id: "course-ui-systems",
        title: "Design Systems with Tailwind and ShadCN",
        instructor: "Leo Martins",
        level: "Intermediate",
        duration: "8h 05m",
        lessons: 39,
        rating: 4.7,
        students: "7.8k",
        price: "$54",
        badge: "Hands-on",
        accent: "from-violet-500 to-fuchsia-400",
      },
    ],
    newest: [
      {
        id: "course-react-query",
        title: "Server State with TanStack Query",
        instructor: "Amina Youssef",
        level: "Intermediate",
        duration: "6h 30m",
        lessons: 28,
        rating: 4.8,
        students: "4.2k",
        price: "$44",
        badge: "New",
        accent: "from-amber-500 to-orange-400",
      },
      {
        id: "course-accessible-react",
        title: "Accessible React Interfaces",
        instructor: "Sam Reed",
        level: "Beginner",
        duration: "5h 50m",
        lessons: 31,
        rating: 4.9,
        students: "3.6k",
        price: "$39",
        badge: "New",
        accent: "from-rose-500 to-pink-400",
      },
      {
        id: "course-testing-next",
        title: "Testing Modern Next.js Workflows",
        instructor: "Yara Saleh",
        level: "Intermediate",
        duration: "7h 15m",
        lessons: 36,
        rating: 4.7,
        students: "5.3k",
        price: "$52",
        badge: "New",
        accent: "from-lime-500 to-emerald-400",
      },
    ],
    trending: [
      {
        id: "course-ai-react",
        title: "AI Product UI with React",
        instructor: "Daniel Kim",
        level: "Advanced",
        duration: "10h 40m",
        lessons: 42,
        rating: 4.9,
        students: "22.1k",
        price: "$79",
        badge: "Trending",
        accent: "from-blue-600 to-violet-500",
      },
      {
        id: "course-performance",
        title: "React Performance Deep Dive",
        instructor: "Iris Novak",
        level: "Advanced",
        duration: "8h 35m",
        lessons: 33,
        rating: 4.8,
        students: "14.9k",
        price: "$64",
        badge: "Trending",
        accent: "from-teal-500 to-cyan-400",
      },
      {
        id: "course-saas-dashboard",
        title: "Build SaaS Dashboards in Next.js",
        instructor: "Karim Nader",
        level: "Intermediate",
        duration: "11h 00m",
        lessons: 51,
        rating: 4.8,
        students: "16.2k",
        price: "$72",
        badge: "Trending",
        accent: "from-slate-700 to-sky-500",
      },
    ],
  },
  instructors: {
    top: [
      {
        id: "instructor-maya",
        name: "Maya Chen",
        role: "Frontend Architect",
        specialty: "React, accessibility, design systems",
        rating: 4.9,
        students: "42k",
        courses: 12,
        accent: "bg-sky-100 text-sky-700",
      },
      {
        id: "instructor-omar",
        name: "Omar Hassan",
        role: "Next.js Consultant",
        specialty: "App Router, server components",
        rating: 4.8,
        students: "35k",
        courses: 9,
        accent: "bg-indigo-100 text-indigo-700",
      },
      {
        id: "instructor-amina",
        name: "Amina Youssef",
        role: "Full-stack Educator",
        specialty: "Data fetching, APIs, SaaS apps",
        rating: 4.9,
        students: "28k",
        courses: 8,
        accent: "bg-emerald-100 text-emerald-700",
      },
    ],
    newest: [
      {
        id: "instructor-yara",
        name: "Yara Saleh",
        role: "Testing Specialist",
        specialty: "Unit tests, integration tests, CI",
        rating: 4.7,
        students: "8k",
        courses: 3,
        accent: "bg-amber-100 text-amber-700",
      },
      {
        id: "instructor-leo",
        name: "Leo Martins",
        role: "Product Designer",
        specialty: "Tailwind, ShadCN, design systems",
        rating: 4.8,
        students: "11k",
        courses: 4,
        accent: "bg-violet-100 text-violet-700",
      },
    ],
  },
  liveClasses: {
    upcoming: [
      {
        id: "live-react-hooks",
        title: "React Hooks Clinic",
        instructor: "Nora Ellis",
        startsAt: "Tomorrow, 6:00 PM",
        duration: "90 min",
        seatsLeft: 18,
        level: "Intermediate",
        accent: "from-cyan-500 to-sky-500",
      },
      {
        id: "live-next-cache",
        title: "Next.js Caching Workshop",
        instructor: "Omar Hassan",
        startsAt: "Fri, 8:30 PM",
        duration: "2h",
        seatsLeft: 12,
        level: "Advanced",
        accent: "from-indigo-500 to-blue-500",
      },
      {
        id: "live-ui-review",
        title: "Frontend UI Review Lab",
        instructor: "Maya Chen",
        startsAt: "Sat, 5:00 PM",
        duration: "75 min",
        seatsLeft: 22,
        level: "All levels",
        accent: "from-emerald-500 to-teal-500",
      },
    ],
    startingSoon: [
      {
        id: "live-ts-debug",
        title: "Debugging TypeScript Errors",
        instructor: "Sam Reed",
        startsAt: "Starts in 35 min",
        duration: "60 min",
        seatsLeft: 7,
        level: "Beginner",
        accent: "from-orange-500 to-amber-400",
      },
      {
        id: "live-query-state",
        title: "Live TanStack Query Patterns",
        instructor: "Amina Youssef",
        startsAt: "Starts in 2h",
        duration: "90 min",
        seatsLeft: 10,
        level: "Intermediate",
        accent: "from-rose-500 to-pink-500",
      },
    ],
  },
};
